// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/index.tsx";
import * as $$0 from "./islands/About.tsx";
import * as $$1 from "./islands/Author.tsx";
import * as $$2 from "./islands/Introduction.tsx";
import * as $$3 from "./islands/Navigator.tsx";

const manifest = {
  routes: {
    "./routes/index.tsx": $0,
  },
  islands: {
    "./islands/About.tsx": $$0,
    "./islands/Author.tsx": $$1,
    "./islands/Introduction.tsx": $$2,
    "./islands/Navigator.tsx": $$3,
  },
  baseUrl: import.meta.url,
};

export default manifest;
