name: Fresh Deno

on:
    # run it on push to the default repository branch
    push:
        branches: [master]
        paths:
            - fresh-deno
    workflow_dispatch:

jobs:
    build-and-push-image:
        name: Build Docker image and push to repositories
        # run only when code is compiling and tests are passing
        runs-on: ubuntu-latest
        env:
            working-directory: ./fresh-deno

        # steps to perform in job
        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            # setup Docker buld action
            - name: Set up Docker Buildx
              id: buildx
              uses: docker/setup-buildx-action@v1

            - name: Push to GCR GitHub Action
              uses: RafikFarhad/push-to-gcr-github-action@v4.1
              with:
                  gcloud_service_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
                  project_id: hoanganhdev
                  image_name: "fresh-copilot"

            - name: Image digest
              run: echo ${{ steps.docker_build.outputs.digest }}
